language: node_js

dist: trusty

node_js:
  - "lts/carbon"

before_install:
  - git clone https://github.com/smartsheet-platform/smartsheet-sdk-tests.git
  - smartsheet-sdk-tests/travis_scripts/install_wiremock.sh

script:
  - smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
  - npm test

branches:
  only:
  - master

after_success:
- npm run coverage
- npm run report-coverage
before_deploy: "echo 'Deploying release to npm'"
deploy:
  provider: npm
  email: api@smartsheet.com
  api_key:
    secure: YcXms4fRUD93C9DPa1KmpxCTyf0aUtTa4tCkp46qRLbsR4YJcrRdTTeIXuim9JYMUBszhSYKh1ic3R0DBqfEWcKzNGE2F7WkPfngozxT1xaFQko/PwyztZOsvDup7HzhKW/Cc2yjQaw9ScA/H/YK+DrVu7DaIamk5g/6dD2gGccZz3ZnkFMOZhiYppEPsnqE2TsqPxz7uvjGUN8iNtYm59UNBEna0Il7iojxJcepVdWj4W7PEgP3YUlSjXJP1aBaYoJCRF8Av/chPv9SYK0ApLRKlDt1mEF4wFrWWQwkSWIrIfQx45f3t/sK3IjURnFH0RSBostYldfAtEkrGZNy575FGrl+Q4fZZAgNE4g0MvLfvYgfqM09S7MEAnzLczFQ0FVKKOPM1Ooe6/EF4N9+wqXg9JFEnWTSXJj08/gngPHqAzUQNEioapviN55uljOnUu6J3413EyGUC8U6Mop5Jsz14tmVdb2js7xfOoMIFMiZWrb0Mjq7u2wDXZcQw85mmuSS4qot2Knkf63QWtCCrOZ/jIfS3etgFjvcUeYEeul9ca5ZwQHy7dCP/KE7Law8lSHWbm1MVsDlw/wwt4lfNutmC3YdIxiuWTnhx5YebgF3AIZiwP6AMi97RzyhfqgWVazz5dd8JOX2xRND4fdU+kShlWtvm2dff2UAxUGKROE=
  on:
    repo: smartsheet-platform/smartsheet-javascript-sdk
    branch: master
after_deploy: "echo 'Finished deployment process'"